/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/item-editor/item-editor.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.ngfactory';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import12 from '../../../../node_modules/@angular/forms/src/directives/radio_control_value_accessor.ngfactory';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '@angular/core/src/linker/view_container';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import18 from '@angular/forms/src/directives/default_value_accessor';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/forms/src/directives/ng_control_status';
import * as import23 from '@ng-bootstrap/ng-bootstrap/buttons/radio';
import * as import24 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import25 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_name.ngfactory';
import * as import26 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import29 from '@angular/common/src/directives/ng_for';
import * as import30 from '@angular/forms/src/directives/reactive_directives/form_group_name';
import * as import31 from '@angular/forms/src/directives/control_container';
import * as import32 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import33 from '../../../../../app/partials/inplace-edit-switch/inplace-edit-switch.component';
import * as import34 from '../partials/inplace-edit-switch/inplace-edit-switch.component.ngfactory';
import * as import35 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import36 from '@angular/common/src/directives/ng_if';
export class Wrapper_ItemEditorComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ItemEditorComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  constructor(p0:any) {
    this._changed = false;
    this._changes = {};
    this.context = new import0.ItemEditorComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_itemId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.itemId = currValue;
      this._changes['itemId'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this._changes);
        this._changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_ItemEditorComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ItemEditorComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ItemEditorComponent>;
  _ItemEditorComponent_0_3:Wrapper_ItemEditorComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemEditorComponent_Host0,renderType_ItemEditorComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'item-editor',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ItemEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._ItemEditorComponent_0_3 = new Wrapper_ItemEditorComponent(this.injectorGet(import9.FormBuilder,this.parentIndex));
    this.compView_0.create(this._ItemEditorComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ItemEditorComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ItemEditorComponent) && (0 === requestNodeIndex))) { return this._ItemEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ItemEditorComponentNgFactory:import8.ComponentFactory<import0.ItemEditorComponent> = new import8.ComponentFactory<import0.ItemEditorComponent>('item-editor',View_ItemEditorComponent_Host0,import0.ItemEditorComponent);
const styles_ItemEditorComponent:any[] = ([] as any[]);
class View_ItemEditorComponent3 extends import2.AppView<any> {
  _el_0:any;
  _NgbActiveLabel_0_3:import10.Wrapper_NgbActiveLabel;
  _text_1:any;
  _el_2:any;
  _DefaultValueAccessor_2_3:import11.Wrapper_DefaultValueAccessor;
  _RadioControlValueAccessor_2_4:import12.Wrapper_RadioControlValueAccessor;
  _NG_VALUE_ACCESSOR_2_5:any[];
  _FormControlName_2_6:import13.Wrapper_FormControlName;
  _NgControl_2_7:any;
  _NgControlStatus_2_8:import14.Wrapper_NgControlStatus;
  _NgbRadio_2_9:import10.Wrapper_NgbRadio;
  _text_3:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_ItemEditorComponent3,renderType_ItemEditorComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_12 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'label',new import3.InlineArray2(2,'class','btn btn-sm btn-primary'),(null as any));
    this._NgbActiveLabel_0_3 = new import10.Wrapper_NgbActiveLabel(this.renderer,new import16.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'input',new import3.InlineArray8(6,'autocomplete','off','formControlName','itemType','type','radio'),(null as any));
    this._DefaultValueAccessor_2_3 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_2));
    this._RadioControlValueAccessor_2_4 = new import12.Wrapper_RadioControlValueAccessor(this.renderer,new import16.ElementRef(this._el_2),this.parentView.parentView.parentView.injectorGet(import17.RadioControlRegistry,this.parentView.parentView.parentIndex),this.injector(2));
    this._NG_VALUE_ACCESSOR_2_5 = [
      this._DefaultValueAccessor_2_3.context,
      this._RadioControlValueAccessor_2_4.context
    ]
    ;
    this._FormControlName_2_6 = new import13.Wrapper_FormControlName((<View_ItemEditorComponent2>this.parentView)._ControlContainer_24_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_2_5);
    this._NgControl_2_7 = this._FormControlName_2_6.context;
    this._NgControlStatus_2_8 = new import14.Wrapper_NgControlStatus(this._NgControl_2_7);
    this._NgbRadio_2_9 = new import10.Wrapper_NgbRadio((<View_ItemEditorComponent2>this.parentView)._NgbRadioGroup_32_4.context,this._NgbActiveLabel_0_3.context,this.renderer,new import16.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(8,'input',(null as any),'blur',(null as any),'change',(null as any),'focus',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (2 === requestNodeIndex))) { return this._DefaultValueAccessor_2_3.context; }
    if (((token === import17.RadioControlValueAccessor) && (2 === requestNodeIndex))) { return this._RadioControlValueAccessor_2_4.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (2 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_2_5; }
    if (((token === import20.FormControlName) && (2 === requestNodeIndex))) { return this._FormControlName_2_6.context; }
    if (((token === import21.NgControl) && (2 === requestNodeIndex))) { return this._NgControl_2_7; }
    if (((token === import22.NgControlStatus) && (2 === requestNodeIndex))) { return this._NgControlStatus_2_8.context; }
    if (((token === import23.NgbRadio) && (2 === requestNodeIndex))) { return this._NgbRadio_2_9.context; }
    if (((token === import23.NgbActiveLabel) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._NgbActiveLabel_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgbActiveLabel_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._DefaultValueAccessor_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_1_0:any = 'itemType';
    this._RadioControlValueAccessor_2_4.check_formControlName(currVal_2_1_0,throwOnChange,false);
    const currVal_2_1_1:any = import3.inlineInterpolate(1,'',this.context.$implicit.value,'');
    this._RadioControlValueAccessor_2_4.check_value(currVal_2_1_1,throwOnChange,false);
    this._RadioControlValueAccessor_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = 'itemType';
    this._FormControlName_2_6.check_name(currVal_2_2_0,throwOnChange,false);
    this._FormControlName_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_8.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_4_0:any = import3.inlineInterpolate(1,'',this.context.$implicit.value,'');
    this._NgbRadio_2_9.check_value(currVal_2_4_0,throwOnChange,false);
    this._NgbRadio_2_9.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_8.checkHost(this,this,this._el_2,throwOnChange);
    this._NgbRadio_2_9.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_12:any = import3.inlineInterpolate(1,'',this.context.$implicit.verbose,'\n                    ');
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_3,currVal_12);
      this._expr_12 = currVal_12;
    }
  }
  destroyInternal():void {
    this._RadioControlValueAccessor_2_4.ngOnDestroy();
    this._FormControlName_2_6.ngOnDestroy();
    this._NgbRadio_2_9.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_2_3.handleEvent(eventName,$event) && result);
    result = (this._RadioControlValueAccessor_2_4.handleEvent(eventName,$event) && result);
    result = (this._NgbRadio_2_9.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemEditorComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import24.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import14.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _DefaultValueAccessor_11_3:import11.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_11_4:any[];
  _FormControlName_11_5:import13.Wrapper_FormControlName;
  _NgControl_11_6:any;
  _NgControlStatus_11_7:import14.Wrapper_NgControlStatus;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _DefaultValueAccessor_21_3:import11.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _FormControlName_21_5:import13.Wrapper_FormControlName;
  _NgControl_21_6:any;
  _NgControlStatus_21_7:import14.Wrapper_NgControlStatus;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _FormGroupName_24_3:import25.Wrapper_FormGroupName;
  _ControlContainer_24_4:any;
  _NgControlStatusGroup_24_5:import14.Wrapper_NgControlStatusGroup;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _DefaultValueAccessor_32_3:import11.Wrapper_DefaultValueAccessor;
  _NgbRadioGroup_32_4:import10.Wrapper_NgbRadioGroup;
  __NG_VALUE_ACCESSOR_32_5:any[];
  _text_33:any;
  _anchor_34:any;
  /*private*/ _vc_34:import15.ViewContainer;
  _TemplateRef_34_5:any;
  _NgFor_34_6:import26.Wrapper_NgFor;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_ItemEditorComponent2,renderType_ItemEditorComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  get _NG_VALUE_ACCESSOR_32_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_32_5 == null)) { (this.__NG_VALUE_ACCESSOR_32_5 = [
      this._DefaultValueAccessor_32_3.context,
      this._NgbRadioGroup_32_4.context
    ]
    ); }
    return this.__NG_VALUE_ACCESSOR_32_5;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'editor',''),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_2_3 = new import24.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',new import3.InlineArray2(2,'for','name'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Name:',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'small',new import3.InlineArray2(2,'class','form-text text-muted'),(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_4,'input',new import3.InlineArray8(8,'class','form-control','formControlName','name','id','name','type','text'),(null as any));
    this._DefaultValueAccessor_11_3 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_11));
    this._NG_VALUE_ACCESSOR_11_4 = [this._DefaultValueAccessor_11_3.context];
    this._FormControlName_11_5 = new import13.Wrapper_FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_11_4);
    this._NgControl_11_6 = this._FormControlName_11_5.context;
    this._NgControlStatus_11_7 = new import14.Wrapper_NgControlStatus(this._NgControl_11_6);
    this._text_12 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'label',new import3.InlineArray2(2,'for','description'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Description:',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_14,'small',new import3.InlineArray2(2,'class','form-text text-muted'),(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_14,'textarea',new import3.InlineArray8(8,'class','form-control','formControlName','description','id','description','type','text'),(null as any));
    this._DefaultValueAccessor_21_3 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._DefaultValueAccessor_21_3.context];
    this._FormControlName_21_5 = new import13.Wrapper_FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._FormControlName_21_5.context;
    this._NgControlStatus_21_7 = new import14.Wrapper_NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray4(4,'class','form-group','formGroupName','itemConfig'),(null as any));
    this._FormGroupName_24_3 = new import25.Wrapper_FormGroupName(this._ControlContainer_2_4,(null as any),(null as any));
    this._ControlContainer_24_4 = this._FormGroupName_24_3.context;
    this._NgControlStatusGroup_24_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_24_4);
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'label',new import3.InlineArray2(2,'for','itemType'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Type:',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_24,'small',new import3.InlineArray2(2,'class','form-text text-muted'),(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray16(10,'class','form-control btn-group-sm btn-group-justified btn-group','data-toggle','buttons','id','itemType','ngDefaultControl','','ngbRadioGroup',''),(null as any));
    this._DefaultValueAccessor_32_3 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_32));
    this._NgbRadioGroup_32_4 = new import10.Wrapper_NgbRadioGroup();
    this._text_33 = this.renderer.createText(this._el_32,'\n                    ',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_32,(null as any));
    this._vc_34 = new import15.ViewContainer(34,32,this,this._anchor_34);
    this._TemplateRef_34_5 = new import27.TemplateRef_(this,34,this._anchor_34);
    this._NgFor_34_6 = new import26.Wrapper_NgFor(this._vc_34.vcRef,this._TemplateRef_34_5,this.parentView.parentView.injectorGet(import28.IterableDiffers,this.parentView.parentIndex),this.parentView.parentView.ref);
    this._text_35 = this.renderer.createText(this._el_32,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_37 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-outline-secondary','type','reset'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Cancel editing',(null as any));
    this._text_40 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'Done',(null as any));
    this._text_43 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this._FormGroupDirective_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_21,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_21));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_32,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_32));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.DefaultValueAccessor) && (11 === requestNodeIndex))) { return this._DefaultValueAccessor_11_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (11 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_11_4; }
    if (((token === import20.FormControlName) && (11 === requestNodeIndex))) { return this._FormControlName_11_5.context; }
    if (((token === import21.NgControl) && (11 === requestNodeIndex))) { return this._NgControl_11_6; }
    if (((token === import22.NgControlStatus) && (11 === requestNodeIndex))) { return this._NgControlStatus_11_7.context; }
    if (((token === import18.DefaultValueAccessor) && (21 === requestNodeIndex))) { return this._DefaultValueAccessor_21_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (21 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import20.FormControlName) && (21 === requestNodeIndex))) { return this._FormControlName_21_5.context; }
    if (((token === import21.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_6; }
    if (((token === import22.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_7.context; }
    if (((token === import27.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import29.NgFor) && (34 === requestNodeIndex))) { return this._NgFor_34_6.context; }
    if (((token === import18.DefaultValueAccessor) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._DefaultValueAccessor_32_3.context; }
    if (((token === import23.NgbRadioGroup) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NgbRadioGroup_32_4.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._NG_VALUE_ACCESSOR_32_5; }
    if (((token === import30.FormGroupName) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._FormGroupName_24_3.context; }
    if (((token === import31.ControlContainer) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ControlContainer_24_4; }
    if (((token === import22.NgControlStatusGroup) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgControlStatusGroup_24_5.context; }
    if (((token === import32.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import31.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ControlContainer_2_4; }
    if (((token === import22.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._NgControlStatusGroup_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.context.itemBaseFormGroup;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    this._DefaultValueAccessor_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    const currVal_11_1_0:any = 'name';
    this._FormControlName_11_5.check_name(currVal_11_1_0,throwOnChange,false);
    this._FormControlName_11_5.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgControlStatus_11_7.ngDoCheck(this,this._el_11,throwOnChange);
    this._DefaultValueAccessor_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_21_1_0:any = 'description';
    this._FormControlName_21_5.check_name(currVal_21_1_0,throwOnChange,false);
    this._FormControlName_21_5.ngDoCheck(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_7.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_24_0_0:any = 'itemConfig';
    this._FormGroupName_24_3.check_name(currVal_24_0_0,throwOnChange,false);
    this._FormGroupName_24_3.ngDoCheck(this,this._el_24,throwOnChange);
    this._NgControlStatusGroup_24_5.ngDoCheck(this,this._el_24,throwOnChange);
    this._DefaultValueAccessor_32_3.ngDoCheck(this,this._el_32,throwOnChange);
    this._NgbRadioGroup_32_4.ngDoCheck(this,this._el_32,throwOnChange);
    const currVal_34_0_0:any = this.parentView.parentView.context.itemTypeOptions;
    this._NgFor_34_6.check_ngForOf(currVal_34_0_0,throwOnChange,false);
    this._NgFor_34_6.ngDoCheck(this,this._anchor_34,throwOnChange);
    this._vc_34.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this,this._el_2,throwOnChange);
    this._NgControlStatus_11_7.checkHost(this,this,this._el_11,throwOnChange);
    this._NgControlStatus_21_7.checkHost(this,this,this._el_21,throwOnChange);
    this._NgControlStatusGroup_24_5.checkHost(this,this,this._el_24,throwOnChange);
  }
  destroyInternal():void {
    this._vc_34.destroyNestedViews();
    this._FormControlName_11_5.ngOnDestroy();
    this._FormControlName_21_5.ngOnDestroy();
    this._FormGroupName_24_3.ngOnDestroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 34)) { return new View_ItemEditorComponent3(this.viewUtils,this,34,this._anchor_34,this._vc_34); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.saveItemDescriptor($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_11_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_21(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_21_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_32(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_32_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemEditorComponent1 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import33.InplaceEditSwitchComponent>;
  _InplaceEditSwitchComponent_0_3:import34.Wrapper_InplaceEditSwitchComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import15.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import35.Wrapper_NgIf;
  _text_12:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import15.ViewContainer) {
    super(View_ItemEditorComponent1,renderType_ItemEditorComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_18 = import1.UNINITIALIZED;
    this._expr_19 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'inplace-edit-switch',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import34.View_InplaceEditSwitchComponent0(this.viewUtils,this,0,this._el_0);
    this._InplaceEditSwitchComponent_0_3 = new import34.Wrapper_InplaceEditSwitchComponent();
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'viewer',''),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_11 = new import15.ViewContainer(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import27.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import35.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_0.create(this._InplaceEditSwitchComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import36.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import33.InplaceEditSwitchComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._InplaceEditSwitchComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.itemEditorIsActive;
    this._InplaceEditSwitchComponent_0_3.check_editState(currVal_0_0_0,throwOnChange,false);
    this._InplaceEditSwitchComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_11_0_0:any = this.parentView.context.itemBaseFormGroup;
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    const currVal_18:any = import3.inlineInterpolate(1,'',((this.parentView.context.item == null)? (null as any): this.parentView.context.item.name),'');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_5,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = import3.inlineInterpolate(1,'',((this.parentView.context.item == null)? (null as any): this.parentView.context.item.description),'');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_8,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this.compView_0.destroy();
    this._InplaceEditSwitchComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {
      cb(this._vc_11.nativeElement,ctx);
      this._vc_11.visitNestedViewRootNodes(cb,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 11)) { return new View_ItemEditorComponent2(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    return (null as any);
  }
}
var renderType_ItemEditorComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ItemEditorComponent,{});
export class View_ItemEditorComponent0 extends import2.AppView<import0.ItemEditorComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import15.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import35.Wrapper_NgIf;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemEditorComponent0,renderType_ItemEditorComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import15.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import27.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import35.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import36.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.item;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_ItemEditorComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}