/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/sequence-editor/sequence-editor.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '@angular/core/src/security';
import * as import14 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import15 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import16 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import17 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/forms/src/directives/default_value_accessor';
import * as import20 from '@angular/forms/src/directives/control_value_accessor';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import22 from '@angular/forms/src/directives/ng_control';
import * as import23 from '@angular/forms/src/directives/ng_control_status';
import * as import24 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import25 from '@angular/forms/src/directives/control_container';
import * as import26 from '../../../../../app/partials/inplace-edit-switch/inplace-edit-switch.component';
import * as import27 from '../partials/inplace-edit-switch/inplace-edit-switch.component.ngfactory';
import * as import28 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import29 from '@angular/core/src/linker/template_ref';
import * as import30 from '@angular/common/src/directives/ng_if';
import * as import31 from '../../../../../app/item-editor/item-editor.component';
import * as import32 from '../item-editor/item-editor.component.ngfactory';
import * as import33 from '../../../../node_modules/ng2-dnd/src/sortable.component.ngfactory';
import * as import34 from 'ng2-dnd/src/dnd.service';
import * as import35 from 'ng2-dnd/src/dnd.config';
import * as import36 from 'ng2-dnd/src/sortable.component';
import * as import37 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import38 from '@angular/common/src/pipes/async_pipe';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from '@angular/common/src/directives/ng_for';
export class Wrapper_SequenceEditorComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SequenceEditorComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.SequenceEditorComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    this.context.ngOnDestroy();
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_SequenceEditorComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_SequenceEditorComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SequenceEditorComponent>;
  _SequenceEditorComponent_0_3:Wrapper_SequenceEditorComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SequenceEditorComponent_Host0,renderType_SequenceEditorComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'sequence-editor',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_SequenceEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._SequenceEditorComponent_0_3 = new Wrapper_SequenceEditorComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex),this.injectorGet(import9.Router,this.parentIndex),this.injectorGet(import10.FormBuilder,this.parentIndex));
    this.compView_0.create(this._SequenceEditorComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._SequenceEditorComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SequenceEditorComponent) && (0 === requestNodeIndex))) { return this._SequenceEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SequenceEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._SequenceEditorComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SequenceEditorComponentNgFactory:import7.ComponentFactory<import0.SequenceEditorComponent> = new import7.ComponentFactory<import0.SequenceEditorComponent>('sequence-editor',View_SequenceEditorComponent_Host0,import0.SequenceEditorComponent);
const styles_SequenceEditorComponent:any[] = ([] as any[]);
class View_SequenceEditorComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SequenceEditorComponent1,renderType_SequenceEditorComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import12.UNINITIALIZED;
    this._expr_3 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'a',new import3.InlineArray2(2,'class','nav-link active'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'#item_',((this.context.$implicit == null)? (null as any): this.context.$implicit._id),'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import13.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'',((this.context.$implicit == null)? (null as any): this.context.$implicit.name),'');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SequenceEditorComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import14.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import15.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _DefaultValueAccessor_12_3:import16.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_12_4:any[];
  _FormControlName_12_5:import17.Wrapper_FormControlName;
  _NgControl_12_6:any;
  _NgControlStatus_12_7:import15.Wrapper_NgControlStatus;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _DefaultValueAccessor_26_3:import16.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_26_4:any[];
  _FormControlName_26_5:import17.Wrapper_FormControlName;
  _NgControl_26_6:any;
  _NgControlStatus_26_7:import15.Wrapper_NgControlStatus;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SequenceEditorComponent3,renderType_SequenceEditorComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'editor',''),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_2_3 = new import14.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import15.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',new import3.InlineArray2(2,'for','sequenceName'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Sequence name:',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'small',new import3.InlineArray2(2,'class','form-text text-muted'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'This name is visible to respondents',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'input',new import3.InlineArray16(10,'class','form-control','formControlName','sequenceName','id','sequenceName','placeholder','Give your sequence a descriptive title','type','text'),(null as any));
    this._DefaultValueAccessor_12_3 = new import16.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_12));
    this._NG_VALUE_ACCESSOR_12_4 = [this._DefaultValueAccessor_12_3.context];
    this._FormControlName_12_5 = new import17.Wrapper_FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_12_4);
    this._NgControl_12_6 = this._FormControlName_12_5.context;
    this._NgControlStatus_12_7 = new import15.Wrapper_NgControlStatus(this._NgControl_12_6);
    this._text_13 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'label',new import3.InlineArray2(2,'for','sequenceDescription'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Description:',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_15,'small',new import3.InlineArray2(2,'class','form-text text-muted'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'This text is ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'span',new import3.InlineArray2(2,'class','caps'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'not',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,' visible to respondents',(null as any));
    this._text_25 = this.renderer.createText(this._el_15,'\n                        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_15,'textarea',new import3.InlineArray16(10,'class','form-control','formControlName','sequenceDescription','id','sequenceDescription','placeholder','Note here all the general information','type','text'),(null as any));
    this._DefaultValueAccessor_26_3 = new import16.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_26));
    this._NG_VALUE_ACCESSOR_26_4 = [this._DefaultValueAccessor_26_3.context];
    this._FormControlName_26_5 = new import17.Wrapper_FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_4);
    this._NgControl_26_6 = this._FormControlName_26_5.context;
    this._NgControlStatus_26_7 = new import15.Wrapper_NgControlStatus(this._NgControl_26_6);
    this._text_27 = this.renderer.createText(this._el_15,'\n                    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-outline-secondary','type','reset'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Cancel editing',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_2,'button',new import3.InlineArray4(4,'class','btn btn-primary','type','submit'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Done',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this._FormGroupDirective_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_12));
    this._FormControlName_12_5.subscribe(this,this.eventHandler(this.handleEvent_12),true);
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_26,new import3.InlineArray8(6,'ngModelChange',(null as any),'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_26));
    this._FormControlName_26_5.subscribe(this,this.eventHandler(this.handleEvent_26),true);
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_29,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_29));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.DefaultValueAccessor) && (12 === requestNodeIndex))) { return this._DefaultValueAccessor_12_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (12 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_12_4; }
    if (((token === import21.FormControlName) && (12 === requestNodeIndex))) { return this._FormControlName_12_5.context; }
    if (((token === import22.NgControl) && (12 === requestNodeIndex))) { return this._NgControl_12_6; }
    if (((token === import23.NgControlStatus) && (12 === requestNodeIndex))) { return this._NgControlStatus_12_7.context; }
    if (((token === import19.DefaultValueAccessor) && (26 === requestNodeIndex))) { return this._DefaultValueAccessor_26_3.context; }
    if (((token === import20.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_4; }
    if (((token === import21.FormControlName) && (26 === requestNodeIndex))) { return this._FormControlName_26_5.context; }
    if (((token === import22.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_6; }
    if (((token === import23.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_7.context; }
    if (((token === import24.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import25.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ControlContainer_2_4; }
    if (((token === import23.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgControlStatusGroup_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.context.sequenceDescriptorFormGroup;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    this._DefaultValueAccessor_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_1_0:any = 'sequenceName';
    this._FormControlName_12_5.check_name(currVal_12_1_0,throwOnChange,false);
    const currVal_12_1_1:any = this.parentView.parentView.context.sequence.name;
    this._FormControlName_12_5.check_model(currVal_12_1_1,throwOnChange,false);
    this._FormControlName_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatus_12_7.ngDoCheck(this,this._el_12,throwOnChange);
    this._DefaultValueAccessor_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_26_1_0:any = 'sequenceDescription';
    this._FormControlName_26_5.check_name(currVal_26_1_0,throwOnChange,false);
    const currVal_26_1_1:any = this.parentView.parentView.context.sequence.description;
    this._FormControlName_26_5.check_model(currVal_26_1_1,throwOnChange,false);
    this._FormControlName_26_5.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_7.ngDoCheck(this,this._el_26,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this,this._el_2,throwOnChange);
    this._NgControlStatus_12_7.checkHost(this,this,this._el_12,throwOnChange);
    this._NgControlStatus_26_7.checkHost(this,this,this._el_26,throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_12_5.ngOnDestroy();
    this._FormControlName_26_5.ngOnDestroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.saveSequenceDescriptor(this.parentView.parentView.context.sequenceDescriptorFormGroup)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.sequence.name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_26(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_26_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.sequence.description = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_29(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.parentView.context.sequenceEditorIsActive = false)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_SequenceEditorComponent2 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import26.InplaceEditSwitchComponent>;
  _InplaceEditSwitchComponent_0_3:import27.Wrapper_InplaceEditSwitchComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import11.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import28.Wrapper_NgIf;
  _text_12:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SequenceEditorComponent2,renderType_SequenceEditorComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_18 = import12.UNINITIALIZED;
    this._expr_19 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'inplace-edit-switch',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import27.View_InplaceEditSwitchComponent0(this.viewUtils,this,0,this._el_0);
    this._InplaceEditSwitchComponent_0_3 = new import27.Wrapper_InplaceEditSwitchComponent();
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'viewer',''),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h1',new import3.InlineArray2(2,'class','display-3'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'p',new import3.InlineArray2(2,'class','lead'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_11 = new import11.ViewContainer(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import29.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import28.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_0.create(this._InplaceEditSwitchComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import30.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import26.InplaceEditSwitchComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._InplaceEditSwitchComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.sequenceEditorIsActive;
    this._InplaceEditSwitchComponent_0_3.check_editState(currVal_0_0_0,throwOnChange,false);
    this._InplaceEditSwitchComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_11_0_0:any = this.parentView.context.sequenceDescriptorFormGroup;
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    const currVal_18:any = import3.inlineInterpolate(1,'',this.parentView.context.sequence.name,'');
    if (import3.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_5,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = import3.inlineInterpolate(1,'',this.parentView.context.sequence.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_8,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this.compView_0.destroy();
    this._InplaceEditSwitchComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {
      cb(this._vc_11.nativeElement,ctx);
      this._vc_11.visitNestedViewRootNodes(cb,ctx);
    }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 11)) { return new View_SequenceEditorComponent3(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.parentView.context.sequenceEditorIsActive = true)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_SequenceEditorComponent5 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import31.ItemEditorComponent>;
  _ItemEditorComponent_0_3:import32.Wrapper_ItemEditorComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SequenceEditorComponent5,renderType_SequenceEditorComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'item-editor',new import3.InlineArray2(2,'class','card-block'),(null as any));
    this.compView_0 = new import32.View_ItemEditorComponent0(this.viewUtils,this,0,this._el_0);
    this._ItemEditorComponent_0_3 = new import32.Wrapper_ItemEditorComponent(this.parentView.parentView.parentView.injectorGet(import10.FormBuilder,this.parentView.parentView.parentIndex));
    this.compView_0.create(this._ItemEditorComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import31.ItemEditorComponent) && (0 === requestNodeIndex))) { return this._ItemEditorComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = ((this.parentView.context.$implicit == null)? (null as any): this.parentView.context.$implicit._id);
    this._ItemEditorComponent_0_3.check_itemId(currVal_0_0_0,throwOnChange,false);
    this._ItemEditorComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_SequenceEditorComponent4 extends import1.AppView<any> {
  _el_0:any;
  _SortableComponent_0_3:import33.Wrapper_SortableComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import11.ViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import28.Wrapper_NgIf;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_SequenceEditorComponent4,renderType_SequenceEditorComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray4(4,'class','card','dnd-sortable',''),(null as any));
    this._SortableComponent_0_3 = new import33.Wrapper_SortableComponent(new import18.ElementRef(this._el_0),this.parentView.parentView.injectorGet(import34.DragDropService,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import35.DragDropConfig,this.parentView.parentIndex),(<View_SequenceEditorComponent0>this.parentView)._SortableContainer_20_3.context,this.parentView.parentView.injectorGet(import34.DragDropSortableService,this.parentView.parentIndex),this.parentView.ref);
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import11.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import29.TemplateRef_(this,2,this._anchor_2);
    this._NgIf_2_6 = new import28.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'onDropSuccess',(null as any)),this.eventHandler(this.handleEvent_0));
    this._SortableComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),false,false,false,false,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import30.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import36.SortableComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._SortableComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.index;
    this._SortableComponent_0_3.check_index(currVal_0_0_0,throwOnChange,false);
    this._SortableComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = ((this.context.$implicit == null)? (null as any): this.context.$implicit._id);
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._SortableComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 2)) { return new View_SequenceEditorComponent5(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'onDropSuccess')) {
      const pd_sub_0:any = ((<any>this.parentView.context.updateSequence($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_SequenceEditorComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_SequenceEditorComponent,{});
export class View_SequenceEditorComponent0 extends import1.AppView<import0.SequenceEditorComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _vc_9:import11.ViewContainer;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import37.Wrapper_NgFor;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import11.ViewContainer;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import28.Wrapper_NgIf;
  _text_19:any;
  _el_20:any;
  _SortableContainer_20_3:import33.Wrapper_SortableContainer;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import11.ViewContainer;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import37.Wrapper_NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _pipe_async_0:import38.AsyncPipe;
  _pipe_itemsSort_1:import0.ItemSortPipe;
  _pipe_async_2:import38.AsyncPipe;
  _pipe_itemsSort_3:import0.ItemSortPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SequenceEditorComponent0,renderType_SequenceEditorComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-12 col-sm-4 col-md-3 sidebar'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Items:',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_2,'nav',new import3.InlineArray2(2,'class','nav flex-column'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._vc_9 = new import11.ViewContainer(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import29.TemplateRef_(this,9,this._anchor_9);
    this._NgFor_9_6 = new import37.Wrapper_NgFor(this._vc_9.vcRef,this._TemplateRef_9_5,this.parentView.injectorGet(import39.IterableDiffers,this.parentIndex),this.ref);
    this._text_10 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_7,'a',new import3.InlineArray2(2,'class','nav-link btn btn-outline-primary'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'+ Add an item',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-12 col-sm-8 col-md-9'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._vc_18 = new import11.ViewContainer(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import29.TemplateRef_(this,18,this._anchor_18);
    this._NgIf_18_6 = new import28.Wrapper_NgIf(this._vc_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_16,'\n\n        ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_16,'div',new import3.InlineArray4(4,'class','col-12','dnd-sortable-container',''),(null as any));
    this._SortableContainer_20_3 = new import33.Wrapper_SortableContainer(new import18.ElementRef(this._el_20),this.parentView.injectorGet(import34.DragDropService,this.parentIndex),this.parentView.injectorGet(import35.DragDropConfig,this.parentIndex),this.ref,this.parentView.injectorGet(import34.DragDropSortableService,this.parentIndex));
    this._text_21 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._vc_22 = new import11.ViewContainer(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import29.TemplateRef_(this,22,this._anchor_22);
    this._NgFor_22_6 = new import37.Wrapper_NgFor(this._vc_22.vcRef,this._TemplateRef_22_5,this.parentView.injectorGet(import39.IterableDiffers,this.parentIndex),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_async_0 = new import38.AsyncPipe(this.ref);
    this._pipe_itemsSort_1 = new import0.ItemSortPipe();
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_11));
    this._pipe_async_2 = new import38.AsyncPipe(this.ref);
    this._pipe_itemsSort_3 = new import0.ItemSortPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import40.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6.context; }
    if (((token === import29.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import30.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6.context; }
    if (((token === import29.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import40.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6.context; }
    if (((token === import36.SortableContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._SortableContainer_20_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import12.ValueUnwrapper();
    valUnwrapper.reset();
    const currVal_9_0_0:any = valUnwrapper.unwrap(this._pipe_itemsSort_1.transform(((this.context.sequence == null)? (null as any): this.context.sequence.itemsSequence),valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.items))));
    this._NgFor_9_6.check_ngForOf(currVal_9_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_9_6.ngDoCheck(this,this._anchor_9,throwOnChange);
    const currVal_18_0_0:any = this.context.sequence;
    this._NgIf_18_6.check_ngIf(currVal_18_0_0,throwOnChange,false);
    this._NgIf_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_20_0_0:any = ((this.context.sequence == null)? (null as any): this.context.sequence.itemsSequence);
    this._SortableContainer_20_3.check_sortableData(currVal_20_0_0,throwOnChange,false);
    this._SortableContainer_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    valUnwrapper.reset();
    const currVal_22_0_0:any = valUnwrapper.unwrap(this._pipe_itemsSort_3.transform(((this.context.sequence == null)? (null as any): this.context.sequence.itemsSequence),valUnwrapper.unwrap(this._pipe_async_2.transform(this.context.items))));
    this._NgFor_22_6.check_ngForOf(currVal_22_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this._NgFor_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_9.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._pipe_async_0.ngOnDestroy();
    this._pipe_async_2.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 9)) { return new View_SequenceEditorComponent1(this.viewUtils,this,9,this._anchor_9,this._vc_9); }
    if ((nodeIndex == 18)) { return new View_SequenceEditorComponent2(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 22)) { return new View_SequenceEditorComponent4(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    return (null as any);
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.createNewItem()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}