/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../../app/item-response/item-response.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import13 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/index';
import * as import24 from 'ng2-dnd/index';
import * as import25 from '@angular/common/src/localization';
import * as import26 from '@angular/core/src/application_init';
import * as import27 from '@angular/core/src/testability/testability';
import * as import28 from '@angular/core/src/application_ref';
import * as import29 from '@angular/core/src/linker/compiler';
import * as import30 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import31 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import32 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import33 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import34 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import35 from '@angular/core/src/animation/animation_queue';
import * as import36 from '@angular/core/src/linker/view_utils';
import * as import37 from '@angular/platform-browser/src/browser/title';
import * as import38 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import39 from '@angular/forms/src/form_builder';
import * as import40 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import43 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import44 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import45 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import46 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import47 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import48 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import49 from './item-response.component.ngfactory';
import * as import50 from '@angular/core/src/i18n/tokens';
import * as import51 from '@angular/core/src/application_tokens';
import * as import52 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import53 from '@angular/platform-browser/src/dom/events/key_events';
import * as import54 from '@angular/core/src/zone/ng_zone';
import * as import55 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import56 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import57 from '@angular/core/src/console';
import * as import58 from '@angular/core/src/error_handler';
import * as import59 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import60 from '@angular/platform-browser/src/dom/animation_driver';
import * as import61 from '@angular/core/src/render/api';
import * as import62 from '@angular/core/src/security';
import * as import63 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import64 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class ItemResponseModuleInjector extends import0.NgModuleInjector<import1.ItemResponseModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ReactiveFormsModule_5:import6.ReactiveFormsModule;
  _NgbAccordionModule_6:import7.NgbAccordionModule;
  _NgbAlertModule_7:import8.NgbAlertModule;
  _NgbButtonsModule_8:import9.NgbButtonsModule;
  _NgbCarouselModule_9:import10.NgbCarouselModule;
  _NgbCollapseModule_10:import11.NgbCollapseModule;
  _NgbDatepickerModule_11:import12.NgbDatepickerModule;
  _NgbDropdownModule_12:import13.NgbDropdownModule;
  _NgbModalModule_13:import14.NgbModalModule;
  _NgbPaginationModule_14:import15.NgbPaginationModule;
  _NgbPopoverModule_15:import16.NgbPopoverModule;
  _NgbProgressbarModule_16:import17.NgbProgressbarModule;
  _NgbRatingModule_17:import18.NgbRatingModule;
  _NgbTabsetModule_18:import19.NgbTabsetModule;
  _NgbTimepickerModule_19:import20.NgbTimepickerModule;
  _NgbTooltipModule_20:import21.NgbTooltipModule;
  _NgbTypeaheadModule_21:import22.NgbTypeaheadModule;
  _NgbModule_22:import23.NgbModule;
  _DndModule_23:import24.DndModule;
  _ItemResponseModule_24:import1.ItemResponseModule;
  __LOCALE_ID_25:any;
  __NgLocalization_26:import25.NgLocaleLocalization;
  _ErrorHandler_27:any;
  _ApplicationInitStatus_28:import26.ApplicationInitStatus;
  _Testability_29:import27.Testability;
  _ApplicationRef__30:import28.ApplicationRef_;
  __ApplicationRef_31:any;
  __Compiler_32:import29.Compiler;
  __APP_ID_33:any;
  __DOCUMENT_34:any;
  __HAMMER_GESTURE_CONFIG_35:import30.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_36:any[];
  __EventManager_37:import31.EventManager;
  _DomSharedStylesHost_38:import32.DomSharedStylesHost;
  __AnimationDriver_39:any;
  __DomRootRenderer_40:import33.DomRootRenderer_;
  __RootRenderer_41:any;
  __DomSanitizer_42:import34.DomSanitizerImpl;
  __Sanitizer_43:any;
  __AnimationQueue_44:import35.AnimationQueue;
  __ViewUtils_45:import36.ViewUtils;
  __IterableDiffers_46:any;
  __KeyValueDiffers_47:any;
  __SharedStylesHost_48:any;
  __Title_49:import37.Title;
  __RadioControlRegistry_50:import38.RadioControlRegistry;
  __FormBuilder_51:import39.FormBuilder;
  __NgbModal_52:import40.NgbModal;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.NgbAlertNgFactory,
      import43.NgbDatepickerNgFactory,
      import44.NgbModalBackdropNgFactory,
      import45.NgbModalWindowNgFactory,
      import46.NgbPopoverWindowNgFactory,
      import47.NgbTooltipWindowNgFactory,
      import48.NgbTypeaheadWindowNgFactory,
      import49.ItemResponseComponentNgFactory
    ]
    ,[import49.ItemResponseComponentNgFactory]);
  }
  get _LOCALE_ID_25():any {
    if ((this.__LOCALE_ID_25 == null)) { (this.__LOCALE_ID_25 = import3._localeFactory(this.parent.get(import50.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_25;
  }
  get _NgLocalization_26():import25.NgLocaleLocalization {
    if ((this.__NgLocalization_26 == null)) { (this.__NgLocalization_26 = new import25.NgLocaleLocalization(this._LOCALE_ID_25)); }
    return this.__NgLocalization_26;
  }
  get _ApplicationRef_31():any {
    if ((this.__ApplicationRef_31 == null)) { (this.__ApplicationRef_31 = this._ApplicationRef__30); }
    return this.__ApplicationRef_31;
  }
  get _Compiler_32():import29.Compiler {
    if ((this.__Compiler_32 == null)) { (this.__Compiler_32 = new import29.Compiler()); }
    return this.__Compiler_32;
  }
  get _APP_ID_33():any {
    if ((this.__APP_ID_33 == null)) { (this.__APP_ID_33 = import51._appIdRandomProviderFactory()); }
    return this.__APP_ID_33;
  }
  get _DOCUMENT_34():any {
    if ((this.__DOCUMENT_34 == null)) { (this.__DOCUMENT_34 = import4._document()); }
    return this.__DOCUMENT_34;
  }
  get _HAMMER_GESTURE_CONFIG_35():import30.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_35 == null)) { (this.__HAMMER_GESTURE_CONFIG_35 = new import30.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_35;
  }
  get _EVENT_MANAGER_PLUGINS_36():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_36 == null)) { (this.__EVENT_MANAGER_PLUGINS_36 = [
      new import52.DomEventsPlugin(),
      new import53.KeyEventsPlugin(),
      new import30.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_35)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_36;
  }
  get _EventManager_37():import31.EventManager {
    if ((this.__EventManager_37 == null)) { (this.__EventManager_37 = new import31.EventManager(this._EVENT_MANAGER_PLUGINS_36,this.parent.get(import54.NgZone))); }
    return this.__EventManager_37;
  }
  get _AnimationDriver_39():any {
    if ((this.__AnimationDriver_39 == null)) { (this.__AnimationDriver_39 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_39;
  }
  get _DomRootRenderer_40():import33.DomRootRenderer_ {
    if ((this.__DomRootRenderer_40 == null)) { (this.__DomRootRenderer_40 = new import33.DomRootRenderer_(this._DOCUMENT_34,this._EventManager_37,this._DomSharedStylesHost_38,this._AnimationDriver_39,this._APP_ID_33)); }
    return this.__DomRootRenderer_40;
  }
  get _RootRenderer_41():any {
    if ((this.__RootRenderer_41 == null)) { (this.__RootRenderer_41 = import55._createConditionalRootRenderer(this._DomRootRenderer_40,this.parent.get(import55.NgProbeToken,(null as any)),this.parent.get(import28.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_41;
  }
  get _DomSanitizer_42():import34.DomSanitizerImpl {
    if ((this.__DomSanitizer_42 == null)) { (this.__DomSanitizer_42 = new import34.DomSanitizerImpl()); }
    return this.__DomSanitizer_42;
  }
  get _Sanitizer_43():any {
    if ((this.__Sanitizer_43 == null)) { (this.__Sanitizer_43 = this._DomSanitizer_42); }
    return this.__Sanitizer_43;
  }
  get _AnimationQueue_44():import35.AnimationQueue {
    if ((this.__AnimationQueue_44 == null)) { (this.__AnimationQueue_44 = new import35.AnimationQueue(this.parent.get(import54.NgZone))); }
    return this.__AnimationQueue_44;
  }
  get _ViewUtils_45():import36.ViewUtils {
    if ((this.__ViewUtils_45 == null)) { (this.__ViewUtils_45 = new import36.ViewUtils(this._RootRenderer_41,this._Sanitizer_43,this._AnimationQueue_44)); }
    return this.__ViewUtils_45;
  }
  get _IterableDiffers_46():any {
    if ((this.__IterableDiffers_46 == null)) { (this.__IterableDiffers_46 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_46;
  }
  get _KeyValueDiffers_47():any {
    if ((this.__KeyValueDiffers_47 == null)) { (this.__KeyValueDiffers_47 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_47;
  }
  get _SharedStylesHost_48():any {
    if ((this.__SharedStylesHost_48 == null)) { (this.__SharedStylesHost_48 = this._DomSharedStylesHost_38); }
    return this.__SharedStylesHost_48;
  }
  get _Title_49():import37.Title {
    if ((this.__Title_49 == null)) { (this.__Title_49 = new import37.Title()); }
    return this.__Title_49;
  }
  get _RadioControlRegistry_50():import38.RadioControlRegistry {
    if ((this.__RadioControlRegistry_50 == null)) { (this.__RadioControlRegistry_50 = new import38.RadioControlRegistry()); }
    return this.__RadioControlRegistry_50;
  }
  get _FormBuilder_51():import39.FormBuilder {
    if ((this.__FormBuilder_51 == null)) { (this.__FormBuilder_51 = new import39.FormBuilder()); }
    return this.__FormBuilder_51;
  }
  get _NgbModal_52():import40.NgbModal {
    if ((this.__NgbModal_52 == null)) { (this.__NgbModal_52 = new import40.NgbModal(this,this,this.parent.get(import56.NgbModalStack))); }
    return this.__NgbModal_52;
  }
  createInternal():import1.ItemResponseModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ReactiveFormsModule_5 = new import6.ReactiveFormsModule();
    this._NgbAccordionModule_6 = new import7.NgbAccordionModule();
    this._NgbAlertModule_7 = new import8.NgbAlertModule();
    this._NgbButtonsModule_8 = new import9.NgbButtonsModule();
    this._NgbCarouselModule_9 = new import10.NgbCarouselModule();
    this._NgbCollapseModule_10 = new import11.NgbCollapseModule();
    this._NgbDatepickerModule_11 = new import12.NgbDatepickerModule();
    this._NgbDropdownModule_12 = new import13.NgbDropdownModule();
    this._NgbModalModule_13 = new import14.NgbModalModule();
    this._NgbPaginationModule_14 = new import15.NgbPaginationModule();
    this._NgbPopoverModule_15 = new import16.NgbPopoverModule();
    this._NgbProgressbarModule_16 = new import17.NgbProgressbarModule();
    this._NgbRatingModule_17 = new import18.NgbRatingModule();
    this._NgbTabsetModule_18 = new import19.NgbTabsetModule();
    this._NgbTimepickerModule_19 = new import20.NgbTimepickerModule();
    this._NgbTooltipModule_20 = new import21.NgbTooltipModule();
    this._NgbTypeaheadModule_21 = new import22.NgbTypeaheadModule();
    this._NgbModule_22 = new import23.NgbModule();
    this._DndModule_23 = new import24.DndModule();
    this._ItemResponseModule_24 = new import1.ItemResponseModule();
    this._ErrorHandler_27 = import4.errorHandler();
    this._ApplicationInitStatus_28 = new import26.ApplicationInitStatus(this.parent.get(import26.APP_INITIALIZER,(null as any)));
    this._Testability_29 = new import27.Testability(this.parent.get(import54.NgZone));
    this._ApplicationRef__30 = new import28.ApplicationRef_(this.parent.get(import54.NgZone),this.parent.get(import57.Console),this,this._ErrorHandler_27,this,this._ApplicationInitStatus_28,this.parent.get(import27.TestabilityRegistry,(null as any)),this._Testability_29);
    this._DomSharedStylesHost_38 = new import32.DomSharedStylesHost(this._DOCUMENT_34);
    return this._ItemResponseModule_24;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import7.NgbAccordionModule)) { return this._NgbAccordionModule_6; }
    if ((token === import8.NgbAlertModule)) { return this._NgbAlertModule_7; }
    if ((token === import9.NgbButtonsModule)) { return this._NgbButtonsModule_8; }
    if ((token === import10.NgbCarouselModule)) { return this._NgbCarouselModule_9; }
    if ((token === import11.NgbCollapseModule)) { return this._NgbCollapseModule_10; }
    if ((token === import12.NgbDatepickerModule)) { return this._NgbDatepickerModule_11; }
    if ((token === import13.NgbDropdownModule)) { return this._NgbDropdownModule_12; }
    if ((token === import14.NgbModalModule)) { return this._NgbModalModule_13; }
    if ((token === import15.NgbPaginationModule)) { return this._NgbPaginationModule_14; }
    if ((token === import16.NgbPopoverModule)) { return this._NgbPopoverModule_15; }
    if ((token === import17.NgbProgressbarModule)) { return this._NgbProgressbarModule_16; }
    if ((token === import18.NgbRatingModule)) { return this._NgbRatingModule_17; }
    if ((token === import19.NgbTabsetModule)) { return this._NgbTabsetModule_18; }
    if ((token === import20.NgbTimepickerModule)) { return this._NgbTimepickerModule_19; }
    if ((token === import21.NgbTooltipModule)) { return this._NgbTooltipModule_20; }
    if ((token === import22.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_21; }
    if ((token === import23.NgbModule)) { return this._NgbModule_22; }
    if ((token === import24.DndModule)) { return this._DndModule_23; }
    if ((token === import1.ItemResponseModule)) { return this._ItemResponseModule_24; }
    if ((token === import50.LOCALE_ID)) { return this._LOCALE_ID_25; }
    if ((token === import25.NgLocalization)) { return this._NgLocalization_26; }
    if ((token === import58.ErrorHandler)) { return this._ErrorHandler_27; }
    if ((token === import26.ApplicationInitStatus)) { return this._ApplicationInitStatus_28; }
    if ((token === import27.Testability)) { return this._Testability_29; }
    if ((token === import28.ApplicationRef_)) { return this._ApplicationRef__30; }
    if ((token === import28.ApplicationRef)) { return this._ApplicationRef_31; }
    if ((token === import29.Compiler)) { return this._Compiler_32; }
    if ((token === import51.APP_ID)) { return this._APP_ID_33; }
    if ((token === import59.DOCUMENT)) { return this._DOCUMENT_34; }
    if ((token === import30.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_35; }
    if ((token === import31.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_36; }
    if ((token === import31.EventManager)) { return this._EventManager_37; }
    if ((token === import32.DomSharedStylesHost)) { return this._DomSharedStylesHost_38; }
    if ((token === import60.AnimationDriver)) { return this._AnimationDriver_39; }
    if ((token === import33.DomRootRenderer)) { return this._DomRootRenderer_40; }
    if ((token === import61.RootRenderer)) { return this._RootRenderer_41; }
    if ((token === import34.DomSanitizer)) { return this._DomSanitizer_42; }
    if ((token === import62.Sanitizer)) { return this._Sanitizer_43; }
    if ((token === import35.AnimationQueue)) { return this._AnimationQueue_44; }
    if ((token === import36.ViewUtils)) { return this._ViewUtils_45; }
    if ((token === import63.IterableDiffers)) { return this._IterableDiffers_46; }
    if ((token === import64.KeyValueDiffers)) { return this._KeyValueDiffers_47; }
    if ((token === import32.SharedStylesHost)) { return this._SharedStylesHost_48; }
    if ((token === import37.Title)) { return this._Title_49; }
    if ((token === import38.RadioControlRegistry)) { return this._RadioControlRegistry_50; }
    if ((token === import39.FormBuilder)) { return this._FormBuilder_51; }
    if ((token === import40.NgbModal)) { return this._NgbModal_52; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__30.ngOnDestroy();
    this._DomSharedStylesHost_38.ngOnDestroy();
  }
}
export const ItemResponseModuleNgFactory:import0.NgModuleFactory<import1.ItemResponseModule> = new import0.NgModuleFactory(ItemResponseModuleInjector,import1.ItemResponseModule);