/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/item-response/item-response.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/core/src/security';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import12 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import13 from '../../../../../app/item-response/item-response-form-btn-group.component';
import * as import14 from './item-response-form-btn-group.component.ngfactory';
import * as import15 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import16 from '@angular/forms/src/directives/control_container';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '../../../../../app/item-response/item-response-form-input.component';
import * as import19 from './item-response-form-input.component.ngfactory';
import * as import20 from '../../../../../app/item-response/item-response-form-textarea.component';
import * as import21 from './item-response-form-textarea.component.ngfactory';
import * as import22 from '../../../../../app/item-response/item-response-form-radio.component';
import * as import23 from './item-response-form-radio.component.ngfactory';
import * as import24 from '../../../../../app/item-response/item-response-form-checkbox.component';
import * as import25 from './item-response-form-checkbox.component.ngfactory';
import * as import26 from '../../../../../app/item-response/item-response-form-listing.component';
import * as import27 from './item-response-form-listing.component.ngfactory';
import * as import28 from '@angular/forms/src/form_builder';
import * as import29 from '../../../../../app/item-response/item-response-form-ordering.component';
import * as import30 from './item-response-form-ordering.component.ngfactory';
import * as import31 from '../../../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from '@angular/common/src/directives/ng_switch';
import * as import34 from '../../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import35 from '@angular/common/src/directives/ng_if';
export class Wrapper_ItemResponseComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ItemResponseComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  subscription1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.ItemResponseComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  check_item(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.item = currValue;
      this._expr_0 = currValue;
    }
  }
  check_responseForm(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.responseForm = currValue;
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.submitCall.subscribe(_eventHandler.bind(view,'submitCall'))); }
    if (emit1) { (this.subscription1 = this.context.resetCall.subscribe(_eventHandler.bind(view,'resetCall'))); }
  }
}
var renderType_ItemResponseComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ItemResponseComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ItemResponseComponent>;
  _ItemResponseComponent_0_3:Wrapper_ItemResponseComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemResponseComponent_Host0,renderType_ItemResponseComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'item-response',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ItemResponseComponent0(this.viewUtils,this,0,this._el_0);
    this._ItemResponseComponent_0_3 = new Wrapper_ItemResponseComponent();
    this.compView_0.create(this._ItemResponseComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ItemResponseComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ItemResponseComponent) && (0 === requestNodeIndex))) { return this._ItemResponseComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemResponseComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ItemResponseComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ItemResponseComponentNgFactory:import8.ComponentFactory<import0.ItemResponseComponent> = new import8.ComponentFactory<import0.ItemResponseComponent>('item-response',View_ItemResponseComponent_Host0,import0.ItemResponseComponent);
const styles_ItemResponseComponent:any[] = ([] as any[]);
class View_ItemResponseComponent2 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent2,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_10 = import1.UNINITIALIZED;
    this._expr_11 = import1.UNINITIALIZED;
    this._expr_12 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_10:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.primaryText,'');
    if (import3.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_3,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.guidanceText,'');
    if (import3.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_6,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.parentView.parentView.context.item.display;
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementProperty(this._el_8,'innerHTML',this.viewUtils.sanitizer.sanitize(import10.SecurityContext.HTML,currVal_12));
      this._expr_12 = currVal_12;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ItemResponseComponent3 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  compView_12:import2.AppView<import13.ItemResponseFormBtnGroupComponent>;
  _FormGroupDirective_12_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_12_4:any;
  _NgControlStatusGroup_12_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormBtnGroupComponent_12_6:import14.Wrapper_ItemResponseFormBtnGroupComponent;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent3,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_24 = import1.UNINITIALIZED;
    this._expr_25 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',new import3.InlineArray2(2,'for','responseInput'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'small',new import3.InlineArray4(4,'class','form-text text-muted','id','responseHelp'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_4,'item-response-form-btn-group',new import3.InlineArray2(2,'class','submission-control'),(null as any));
    this.compView_12 = new import14.View_ItemResponseFormBtnGroupComponent0(this.viewUtils,this,12,this._el_12);
    this._FormGroupDirective_12_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_12_4 = this._FormGroupDirective_12_3.context;
    this._NgControlStatusGroup_12_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_12_4);
    this._ItemResponseFormBtnGroupComponent_12_6 = new import14.Wrapper_ItemResponseFormBtnGroupComponent();
    this.compView_12.create(this._ItemResponseFormBtnGroupComponent_12_6.context);
    this._text_13 = this.renderer.createText(this._el_4,'\n\n                ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_12,new import3.InlineArray8(8,'submitCall',(null as any),'resetCall',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_12));
    this._ItemResponseFormBtnGroupComponent_12_6.subscribe(this,this.eventHandler(this.handleEvent_12),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (12 === requestNodeIndex))) { return this._FormGroupDirective_12_3.context; }
    if (((token === import16.ControlContainer) && (12 === requestNodeIndex))) { return this._ControlContainer_12_4; }
    if (((token === import17.NgControlStatusGroup) && (12 === requestNodeIndex))) { return this._NgControlStatusGroup_12_5.context; }
    if (((token === import13.ItemResponseFormBtnGroupComponent) && (12 === requestNodeIndex))) { return this._ItemResponseFormBtnGroupComponent_12_6.context; }
    if (((token === import15.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgControlStatusGroup_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_12_0_0:any = this.parentView.parentView.context.responseForm;
    this._FormGroupDirective_12_3.check_form(currVal_12_0_0,throwOnChange,false);
    this._FormGroupDirective_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_12_5.ngDoCheck(this,this._el_12,throwOnChange);
    const currVal_12_2_0:any = 'responseInput';
    this._ItemResponseFormBtnGroupComponent_12_6.check_controlName(currVal_12_2_0,throwOnChange,false);
    const currVal_12_2_1:any = this.parentView.parentView.context.responseForm;
    this._ItemResponseFormBtnGroupComponent_12_6.check_formGroup(currVal_12_2_1,throwOnChange,false);
    this._ItemResponseFormBtnGroupComponent_12_6.ngDoCheck(this,this._el_12,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_24:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.primaryText,'');
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_7,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.guidanceText,'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_10,currVal_25);
      this._expr_25 = currVal_25;
    }
    this._NgControlStatusGroup_12_5.checkHost(this,this.compView_12,this._el_12,throwOnChange);
    this.compView_12.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_12.destroy();
    this._FormGroupDirective_12_3.ngOnDestroy();
    this._ItemResponseFormBtnGroupComponent_12_6.ngOnDestroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'submitCall')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.submitCall.emit($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'resetCall')) {
      const pd_sub_1:any = ((<any>this.parentView.parentView.context.resetCall.emit($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}
class View_ItemResponseComponent5 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import18.ItemResponseFormInputComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormInputComponent_2_6:import19.Wrapper_ItemResponseFormInputComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent5,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-input',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import19.View_ItemResponseFormInputComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormInputComponent_2_6 = new import19.Wrapper_ItemResponseFormInputComponent();
    this.compView_2.create(this._ItemResponseFormInputComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import18.ItemResponseFormInputComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormInputComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = 'responseInput';
    this._ItemResponseFormInputComponent_2_6.check_controlName(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseInput';
    this._ItemResponseFormInputComponent_2_6.check_inputId(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = this.parentView.parentView.parentView.context.item.itemConfig.inputType;
    this._ItemResponseFormInputComponent_2_6.check_inputType(currVal_2_2_2,throwOnChange,false);
    const currVal_2_2_3:any = 'responseHelp';
    this._ItemResponseFormInputComponent_2_6.check_describedby(currVal_2_2_3,throwOnChange,false);
    const currVal_2_2_4:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormInputComponent_2_6.check_formGroup(currVal_2_2_4,throwOnChange,false);
    this._ItemResponseFormInputComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormInputComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent6 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import20.ItemResponseFormTextareaComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormTextareaComponent_2_6:import21.Wrapper_ItemResponseFormTextareaComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent6,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-textarea',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import21.View_ItemResponseFormTextareaComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormTextareaComponent_2_6 = new import21.Wrapper_ItemResponseFormTextareaComponent();
    this.compView_2.create(this._ItemResponseFormTextareaComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import20.ItemResponseFormTextareaComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormTextareaComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = 'responseInput';
    this._ItemResponseFormTextareaComponent_2_6.check_controlName(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseInput';
    this._ItemResponseFormTextareaComponent_2_6.check_inputId(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = this.parentView.parentView.parentView.context.item.itemConfig.inputType;
    this._ItemResponseFormTextareaComponent_2_6.check_inputType(currVal_2_2_2,throwOnChange,false);
    const currVal_2_2_3:any = 'responseHelp';
    this._ItemResponseFormTextareaComponent_2_6.check_describedby(currVal_2_2_3,throwOnChange,false);
    const currVal_2_2_4:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormTextareaComponent_2_6.check_formGroup(currVal_2_2_4,throwOnChange,false);
    this._ItemResponseFormTextareaComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormTextareaComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent7 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import22.ItemResponseFormRadioComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormRadioComponent_2_6:import23.Wrapper_ItemResponseFormRadioComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent7,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-radio',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import23.View_ItemResponseFormRadioComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormRadioComponent_2_6 = new import23.Wrapper_ItemResponseFormRadioComponent();
    this.compView_2.create(this._ItemResponseFormRadioComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import22.ItemResponseFormRadioComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormRadioComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = this.parentView.parentView.parentView.context.item.choices;
    this._ItemResponseFormRadioComponent_2_6.check_choices(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseInput';
    this._ItemResponseFormRadioComponent_2_6.check_controlName(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = 'responseHelp';
    this._ItemResponseFormRadioComponent_2_6.check_describedby(currVal_2_2_2,throwOnChange,false);
    const currVal_2_2_3:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormRadioComponent_2_6.check_formGroup(currVal_2_2_3,throwOnChange,false);
    this._ItemResponseFormRadioComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormRadioComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent8 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import24.ItemResponseFormCheckboxComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormCheckboxComponent_2_6:import25.Wrapper_ItemResponseFormCheckboxComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent8,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-checkbox',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import25.View_ItemResponseFormCheckboxComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormCheckboxComponent_2_6 = new import25.Wrapper_ItemResponseFormCheckboxComponent();
    this.compView_2.create(this._ItemResponseFormCheckboxComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import24.ItemResponseFormCheckboxComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormCheckboxComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = this.parentView.parentView.parentView.context.item.choices;
    this._ItemResponseFormCheckboxComponent_2_6.check_choices(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseHelp';
    this._ItemResponseFormCheckboxComponent_2_6.check_describedby(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormCheckboxComponent_2_6.check_formGroup(currVal_2_2_2,throwOnChange,false);
    this._ItemResponseFormCheckboxComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormCheckboxComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent9 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import26.ItemResponseFormListingComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormListingComponent_2_6:import27.Wrapper_ItemResponseFormListingComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent9,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-listing',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import27.View_ItemResponseFormListingComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormListingComponent_2_6 = new import27.Wrapper_ItemResponseFormListingComponent(this.parentView.parentView.parentView.injectorGet(import28.FormBuilder,this.parentView.parentView.parentIndex));
    this.compView_2.create(this._ItemResponseFormListingComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import26.ItemResponseFormListingComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormListingComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = this.parentView.parentView.parentView.context.item.choices;
    this._ItemResponseFormListingComponent_2_6.check_choices(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseHelp';
    this._ItemResponseFormListingComponent_2_6.check_describedby(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormListingComponent_2_6.check_formGroup(currVal_2_2_2,throwOnChange,false);
    this._ItemResponseFormListingComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormListingComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent10 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import29.ItemResponseFormOrderingComponent>;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _ItemResponseFormOrderingComponent_2_6:import30.Wrapper_ItemResponseFormOrderingComponent;
  _text_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent10,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'item-response-form-ordering',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import30.View_ItemResponseFormOrderingComponent0(this.viewUtils,this,2,this._el_2);
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._ItemResponseFormOrderingComponent_2_6 = new import30.Wrapper_ItemResponseFormOrderingComponent();
    this.compView_2.create(this._ItemResponseFormOrderingComponent_2_6.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.FormGroupDirective) && (2 === requestNodeIndex))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && (2 === requestNodeIndex))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && (2 === requestNodeIndex))) { return this._NgControlStatusGroup_2_5.context; }
    if (((token === import29.ItemResponseFormOrderingComponent) && (2 === requestNodeIndex))) { return this._ItemResponseFormOrderingComponent_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = this.parentView.parentView.parentView.context.item.choices;
    this._ItemResponseFormOrderingComponent_2_6.check_choices(currVal_2_2_0,throwOnChange,false);
    const currVal_2_2_1:any = 'responseHelp';
    this._ItemResponseFormOrderingComponent_2_6.check_describedby(currVal_2_2_1,throwOnChange,false);
    const currVal_2_2_2:any = this.parentView.parentView.parentView.context.responseForm;
    this._ItemResponseFormOrderingComponent_2_6.check_formGroup(currVal_2_2_2,throwOnChange,false);
    this._ItemResponseFormOrderingComponent_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this._FormGroupDirective_2_3.ngOnDestroy();
    this._ItemResponseFormOrderingComponent_2_6.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_ItemResponseComponent4 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import11.Wrapper_FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.Wrapper_NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _NgSwitch_4_3:import31.Wrapper_NgSwitch;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import9.ViewContainer;
  _TemplateRef_12_5:any;
  _NgSwitchCase_12_6:import31.Wrapper_NgSwitchCase;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import9.ViewContainer;
  _TemplateRef_14_5:any;
  _NgSwitchCase_14_6:import31.Wrapper_NgSwitchCase;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import9.ViewContainer;
  _TemplateRef_16_5:any;
  _NgSwitchCase_16_6:import31.Wrapper_NgSwitchCase;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import9.ViewContainer;
  _TemplateRef_18_5:any;
  _NgSwitchCase_18_6:import31.Wrapper_NgSwitchCase;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import9.ViewContainer;
  _TemplateRef_20_5:any;
  _NgSwitchCase_20_6:import31.Wrapper_NgSwitchCase;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import9.ViewContainer;
  _TemplateRef_22_5:any;
  _NgSwitchCase_22_6:import31.Wrapper_NgSwitchCase;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent4,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_48 = import1.UNINITIALIZED;
    this._expr_49 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_2_3 = new import11.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3.context;
    this._NgControlStatusGroup_2_5 = new import12.Wrapper_NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'fieldset',new import3.InlineArray2(2,'class','form-group'),(null as any));
    this._NgSwitch_4_3 = new import31.Wrapper_NgSwitch();
    this._text_5 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',new import3.InlineArray2(2,'for','responseInput'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_4,'small',new import3.InlineArray4(4,'class','form-text text-muted','id','responseHelp'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_12 = new import9.ViewContainer(12,4,this,this._anchor_12);
    this._TemplateRef_12_5 = new import32.TemplateRef_(this,12,this._anchor_12);
    this._NgSwitchCase_12_6 = new import31.Wrapper_NgSwitchCase(this._vc_12.vcRef,this._TemplateRef_12_5,this._NgSwitch_4_3.context);
    this._text_13 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_14 = new import9.ViewContainer(14,4,this,this._anchor_14);
    this._TemplateRef_14_5 = new import32.TemplateRef_(this,14,this._anchor_14);
    this._NgSwitchCase_14_6 = new import31.Wrapper_NgSwitchCase(this._vc_14.vcRef,this._TemplateRef_14_5,this._NgSwitch_4_3.context);
    this._text_15 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_16 = new import9.ViewContainer(16,4,this,this._anchor_16);
    this._TemplateRef_16_5 = new import32.TemplateRef_(this,16,this._anchor_16);
    this._NgSwitchCase_16_6 = new import31.Wrapper_NgSwitchCase(this._vc_16.vcRef,this._TemplateRef_16_5,this._NgSwitch_4_3.context);
    this._text_17 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_18 = new import9.ViewContainer(18,4,this,this._anchor_18);
    this._TemplateRef_18_5 = new import32.TemplateRef_(this,18,this._anchor_18);
    this._NgSwitchCase_18_6 = new import31.Wrapper_NgSwitchCase(this._vc_18.vcRef,this._TemplateRef_18_5,this._NgSwitch_4_3.context);
    this._text_19 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_20 = new import9.ViewContainer(20,4,this,this._anchor_20);
    this._TemplateRef_20_5 = new import32.TemplateRef_(this,20,this._anchor_20);
    this._NgSwitchCase_20_6 = new import31.Wrapper_NgSwitchCase(this._vc_20.vcRef,this._TemplateRef_20_5,this._NgSwitch_4_3.context);
    this._text_21 = this.renderer.createText(this._el_4,'\n\n                    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_4,(null as any));
    this._vc_22 = new import9.ViewContainer(22,4,this,this._anchor_22);
    this._TemplateRef_22_5 = new import32.TemplateRef_(this,22,this._anchor_22);
    this._NgSwitchCase_22_6 = new import31.Wrapper_NgSwitchCase(this._vc_22.vcRef,this._TemplateRef_22_5,this._NgSwitch_4_3.context);
    this._text_23 = this.renderer.createText(this._el_4,'\n\n\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_2));
    this._FormGroupDirective_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import33.NgSwitchCase) && (12 === requestNodeIndex))) { return this._NgSwitchCase_12_6.context; }
    if (((token === import32.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import33.NgSwitchCase) && (14 === requestNodeIndex))) { return this._NgSwitchCase_14_6.context; }
    if (((token === import32.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import33.NgSwitchCase) && (16 === requestNodeIndex))) { return this._NgSwitchCase_16_6.context; }
    if (((token === import32.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import33.NgSwitchCase) && (18 === requestNodeIndex))) { return this._NgSwitchCase_18_6.context; }
    if (((token === import32.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import33.NgSwitchCase) && (20 === requestNodeIndex))) { return this._NgSwitchCase_20_6.context; }
    if (((token === import32.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import33.NgSwitchCase) && (22 === requestNodeIndex))) { return this._NgSwitchCase_22_6.context; }
    if (((token === import33.NgSwitch) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._NgSwitch_4_3.context; }
    if (((token === import15.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._FormGroupDirective_2_3.context; }
    if (((token === import16.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgControlStatusGroup_2_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.parentView.context.responseForm;
    this._FormGroupDirective_2_3.check_form(currVal_2_0_0,throwOnChange,false);
    this._FormGroupDirective_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatusGroup_2_5.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = this.parentView.parentView.context.item.itemConfig.itemType;
    this._NgSwitch_4_3.check_ngSwitch(currVal_4_0_0,throwOnChange,false);
    this._NgSwitch_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_12_0_0:any = 'input';
    this._NgSwitchCase_12_6.check_ngSwitchCase(currVal_12_0_0,throwOnChange,false);
    this._NgSwitchCase_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_14_0_0:any = 'text';
    this._NgSwitchCase_14_6.check_ngSwitchCase(currVal_14_0_0,throwOnChange,false);
    this._NgSwitchCase_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    const currVal_16_0_0:any = 'single-choice';
    this._NgSwitchCase_16_6.check_ngSwitchCase(currVal_16_0_0,throwOnChange,false);
    this._NgSwitchCase_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_18_0_0:any = 'multiple-choice';
    this._NgSwitchCase_18_6.check_ngSwitchCase(currVal_18_0_0,throwOnChange,false);
    this._NgSwitchCase_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_20_0_0:any = 'listing';
    this._NgSwitchCase_20_6.check_ngSwitchCase(currVal_20_0_0,throwOnChange,false);
    this._NgSwitchCase_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    const currVal_22_0_0:any = 'ordering';
    this._NgSwitchCase_22_6.check_ngSwitchCase(currVal_22_0_0,throwOnChange,false);
    this._NgSwitchCase_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    this._NgControlStatusGroup_2_5.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_48:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.primaryText,'');
    if (import3.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setText(this._text_7,currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = import3.inlineInterpolate(1,'',this.parentView.parentView.context.item.guidanceText,'');
    if (import3.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setText(this._text_10,currVal_49);
      this._expr_49 = currVal_49;
    }
  }
  destroyInternal():void {
    this._vc_12.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._FormGroupDirective_2_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 12)) { return new View_ItemResponseComponent5(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 14)) { return new View_ItemResponseComponent6(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 16)) { return new View_ItemResponseComponent7(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 18)) { return new View_ItemResponseComponent8(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 20)) { return new View_ItemResponseComponent9(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    if ((nodeIndex == 22)) { return new View_ItemResponseComponent10(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    return (null as any);
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_2_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.submitCall.emit($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ItemResponseComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgSwitch_2_3:import31.Wrapper_NgSwitch;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import9.ViewContainer;
  _TemplateRef_4_5:any;
  _NgSwitchCase_4_6:import31.Wrapper_NgSwitchCase;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import9.ViewContainer;
  _TemplateRef_6_5:any;
  _NgSwitchCase_6_6:import31.Wrapper_NgSwitchCase;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import9.ViewContainer;
  _TemplateRef_8_5:any;
  _NgSwitchDefault_8_6:import31.Wrapper_NgSwitchDefault;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_ItemResponseComponent1,renderType_ItemResponseComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','col-12'),(null as any));
    this._NgSwitch_2_3 = new import31.Wrapper_NgSwitch();
    this._text_3 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_4 = new import9.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import32.TemplateRef_(this,4,this._anchor_4);
    this._NgSwitchCase_4_6 = new import31.Wrapper_NgSwitchCase(this._vc_4.vcRef,this._TemplateRef_4_5,this._NgSwitch_2_3.context);
    this._text_5 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_6 = new import9.ViewContainer(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import32.TemplateRef_(this,6,this._anchor_6);
    this._NgSwitchCase_6_6 = new import31.Wrapper_NgSwitchCase(this._vc_6.vcRef,this._TemplateRef_6_5,this._NgSwitch_2_3.context);
    this._text_7 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._vc_8 = new import9.ViewContainer(8,2,this,this._anchor_8);
    this._TemplateRef_8_5 = new import32.TemplateRef_(this,8,this._anchor_8);
    this._NgSwitchDefault_8_6 = new import31.Wrapper_NgSwitchDefault(this._vc_8.vcRef,this._TemplateRef_8_5,this._NgSwitch_2_3.context);
    this._text_9 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import33.NgSwitchCase) && (4 === requestNodeIndex))) { return this._NgSwitchCase_4_6.context; }
    if (((token === import32.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import33.NgSwitchCase) && (6 === requestNodeIndex))) { return this._NgSwitchCase_6_6.context; }
    if (((token === import32.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import33.NgSwitchDefault) && (8 === requestNodeIndex))) { return this._NgSwitchDefault_8_6.context; }
    if (((token === import33.NgSwitch) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgSwitch_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parentView.context.item.itemConfig.itemType;
    this._NgSwitch_2_3.check_ngSwitch(currVal_2_0_0,throwOnChange,false);
    this._NgSwitch_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = 'display';
    this._NgSwitchCase_4_6.check_ngSwitchCase(currVal_4_0_0,throwOnChange,false);
    this._NgSwitchCase_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:any = 'yes-no';
    this._NgSwitchCase_6_6.check_ngSwitchCase(currVal_6_0_0,throwOnChange,false);
    this._NgSwitchCase_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    this._NgSwitchDefault_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this._vc_6.destroyNestedViews();
    this._vc_8.destroyNestedViews();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 4)) { return new View_ItemResponseComponent2(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 6)) { return new View_ItemResponseComponent3(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    if ((nodeIndex == 8)) { return new View_ItemResponseComponent4(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    return (null as any);
  }
}
var renderType_ItemResponseComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ItemResponseComponent,{});
export class View_ItemResponseComponent0 extends import2.AppView<import0.ItemResponseComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import9.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import34.Wrapper_NgIf;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemResponseComponent0,renderType_ItemResponseComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import9.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import32.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import34.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._anchor_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import35.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.item;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_ItemResponseComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}