/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/item-response/item-response-form-btn-group.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import10 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import11 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import12 from '../../../../node_modules/@ng-bootstrap/ng-bootstrap/buttons/radio.ngfactory';
import * as import13 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@ng-bootstrap/ng-bootstrap/buttons/radio';
import * as import16 from '@angular/forms/src/directives/default_value_accessor';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/ng_control_status';
import * as import21 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import22 from '@angular/forms/src/directives/control_container';
export class Wrapper_ItemResponseFormBtnGroupComponent {
  /*private*/ _eventHandler:Function;
  context:import0.ItemResponseFormBtnGroupComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  subscription0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.ItemResponseFormBtnGroupComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
    this._expr_3 = import1.UNINITIALIZED;
    this._expr_4 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_controlName(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.controlName = currValue;
      this._expr_0 = currValue;
    }
  }
  check_inputId(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.inputId = currValue;
      this._expr_1 = currValue;
    }
  }
  check_inputType(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this._changed = true;
      this.context.inputType = currValue;
      this._expr_2 = currValue;
    }
  }
  check_describedby(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_3,currValue))) {
      this._changed = true;
      this.context.describedby = currValue;
      this._expr_3 = currValue;
    }
  }
  check_formGroup(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_4,currValue))) {
      this._changed = true;
      this.context.formGroup = currValue;
      this._expr_4 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.submitCall.subscribe(_eventHandler.bind(view,'submitCall'))); }
  }
}
var renderType_ItemResponseFormBtnGroupComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_ItemResponseFormBtnGroupComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.ItemResponseFormBtnGroupComponent>;
  _ItemResponseFormBtnGroupComponent_0_3:Wrapper_ItemResponseFormBtnGroupComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemResponseFormBtnGroupComponent_Host0,renderType_ItemResponseFormBtnGroupComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'item-response-form-btn-group',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ItemResponseFormBtnGroupComponent0(this.viewUtils,this,0,this._el_0);
    this._ItemResponseFormBtnGroupComponent_0_3 = new Wrapper_ItemResponseFormBtnGroupComponent();
    this.compView_0.create(this._ItemResponseFormBtnGroupComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._ItemResponseFormBtnGroupComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ItemResponseFormBtnGroupComponent) && (0 === requestNodeIndex))) { return this._ItemResponseFormBtnGroupComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemResponseFormBtnGroupComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._ItemResponseFormBtnGroupComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ItemResponseFormBtnGroupComponentNgFactory:import8.ComponentFactory<import0.ItemResponseFormBtnGroupComponent> = new import8.ComponentFactory<import0.ItemResponseFormBtnGroupComponent>('item-response-form-btn-group',View_ItemResponseFormBtnGroupComponent_Host0,import0.ItemResponseFormBtnGroupComponent);
const styles_ItemResponseFormBtnGroupComponent:any[] = ([] as any[]);
var renderType_ItemResponseFormBtnGroupComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_ItemResponseFormBtnGroupComponent,{});
export class View_ItemResponseFormBtnGroupComponent0 extends import2.AppView<import0.ItemResponseFormBtnGroupComponent> {
  _el_0:any;
  _FormGroupDirective_0_3:import9.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import10.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _DefaultValueAccessor_2_3:import11.Wrapper_DefaultValueAccessor;
  _NgbRadioGroup_2_4:import12.Wrapper_NgbRadioGroup;
  _NG_VALUE_ACCESSOR_2_5:any[];
  _FormControlName_2_6:import13.Wrapper_FormControlName;
  _NgControl_2_7:any;
  _NgControlStatus_2_8:import10.Wrapper_NgControlStatus;
  _text_3:any;
  _el_4:any;
  _NgbActiveLabel_4_3:import12.Wrapper_NgbActiveLabel;
  _text_5:any;
  _el_6:any;
  _NgbRadio_6_3:import12.Wrapper_NgbRadio;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgbActiveLabel_9_3:import12.Wrapper_NgbActiveLabel;
  _text_10:any;
  _el_11:any;
  _NgbRadio_11_3:import12.Wrapper_NgbRadio;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgbActiveLabel_14_3:import12.Wrapper_NgbActiveLabel;
  _text_15:any;
  _el_16:any;
  _NgbRadio_16_3:import12.Wrapper_NgbRadio;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_ItemResponseFormBtnGroupComponent0,renderType_ItemResponseFormBtnGroupComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_35 = import1.UNINITIALIZED;
    this._expr_36 = import1.UNINITIALIZED;
    this._expr_37 = import1.UNINITIALIZED;
    this._expr_38 = import1.UNINITIALIZED;
    this._expr_39 = import1.UNINITIALIZED;
    this._expr_40 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._FormGroupDirective_0_3 = new import9.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import10.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray8(8,'class','btn-group btn-group-justified btn-group','data-toggle','buttons','ngDefaultControl','','ngbRadioGroup',''),(null as any));
    this._DefaultValueAccessor_2_3 = new import11.Wrapper_DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_2));
    this._NgbRadioGroup_2_4 = new import12.Wrapper_NgbRadioGroup();
    this._NG_VALUE_ACCESSOR_2_5 = [
      this._DefaultValueAccessor_2_3.context,
      this._NgbRadioGroup_2_4.context
    ]
    ;
    this._FormControlName_2_6 = new import13.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_2_5);
    this._NgControl_2_7 = this._FormControlName_2_6.context;
    this._NgControlStatus_2_8 = new import10.Wrapper_NgControlStatus(this._NgControl_2_7);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'label',new import3.InlineArray2(2,'class','btn btn-lg btn-primary'),(null as any));
    this._NgbActiveLabel_4_3 = new import12.Wrapper_NgbActiveLabel(this.renderer,new import14.ElementRef(this._el_4));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'input',new import3.InlineArray8(6,'autocomplete','off','type','radio','value','No'),(null as any));
    this._NgbRadio_6_3 = new import12.Wrapper_NgbRadio(this._NgbRadioGroup_2_4.context,this._NgbActiveLabel_4_3.context,this.renderer,new import14.ElementRef(this._el_6));
    this._text_7 = this.renderer.createText(this._el_4,'No\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_2,'label',new import3.InlineArray2(2,'class','btn btn-lg btn-secondary'),(null as any));
    this._NgbActiveLabel_9_3 = new import12.Wrapper_NgbActiveLabel(this.renderer,new import14.ElementRef(this._el_9));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,this._el_9,'input',new import3.InlineArray8(6,'autocomplete','off','type','radio','value','N/A'),(null as any));
    this._NgbRadio_11_3 = new import12.Wrapper_NgbRadio(this._NgbRadioGroup_2_4.context,this._NgbActiveLabel_9_3.context,this.renderer,new import14.ElementRef(this._el_11));
    this._text_12 = this.renderer.createText(this._el_9,'N/A\n        ',(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_2,'label',new import3.InlineArray2(2,'class','btn btn-lg btn-primary'),(null as any));
    this._NgbActiveLabel_14_3 = new import12.Wrapper_NgbActiveLabel(this.renderer,new import14.ElementRef(this._el_14));
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'input',new import3.InlineArray8(6,'autocomplete','off','type','radio','value','Yes'),(null as any));
    this._NgbRadio_16_3 = new import12.Wrapper_NgbRadio(this._NgbRadioGroup_2_4.context,this._NgbActiveLabel_14_3.context,this.renderer,new import14.ElementRef(this._el_16));
    this._text_17 = this.renderer.createText(this._el_14,'Yes\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_0));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray4(4,'input',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_6,new import3.InlineArray8(6,'change',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_6));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_11,new import3.InlineArray8(6,'change',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_16,new import3.InlineArray8(6,'change',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_16));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.NgbRadio) && (6 === requestNodeIndex))) { return this._NgbRadio_6_3.context; }
    if (((token === import15.NgbActiveLabel) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgbActiveLabel_4_3.context; }
    if (((token === import15.NgbRadio) && (11 === requestNodeIndex))) { return this._NgbRadio_11_3.context; }
    if (((token === import15.NgbActiveLabel) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgbActiveLabel_9_3.context; }
    if (((token === import15.NgbRadio) && (16 === requestNodeIndex))) { return this._NgbRadio_16_3.context; }
    if (((token === import15.NgbActiveLabel) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgbActiveLabel_14_3.context; }
    if (((token === import16.DefaultValueAccessor) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._DefaultValueAccessor_2_3.context; }
    if (((token === import15.NgbRadioGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgbRadioGroup_2_4.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NG_VALUE_ACCESSOR_2_5; }
    if (((token === import18.FormControlName) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._FormControlName_2_6.context; }
    if (((token === import19.NgControl) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgControl_2_7; }
    if (((token === import20.NgControlStatus) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgControlStatus_2_8.context; }
    if (((token === import21.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import22.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ControlContainer_0_4; }
    if (((token === import20.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.formGroup;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this._DefaultValueAccessor_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgbRadioGroup_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_2_2_0:any = this.context.controlName;
    this._FormControlName_2_6.check_name(currVal_2_2_0,throwOnChange,false);
    this._FormControlName_2_6.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgControlStatus_2_8.ngDoCheck(this,this._el_2,throwOnChange);
    this._NgbActiveLabel_4_3.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_6_0_0:any = 'No';
    this._NgbRadio_6_3.check_value(currVal_6_0_0,throwOnChange,false);
    this._NgbRadio_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._NgbActiveLabel_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:any = 'N/A';
    this._NgbRadio_11_3.check_value(currVal_11_0_0,throwOnChange,false);
    this._NgbRadio_11_3.ngDoCheck(this,this._el_11,throwOnChange);
    this._NgbActiveLabel_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_16_0_0:any = 'Yes';
    this._NgbRadio_16_3.check_value(currVal_16_0_0,throwOnChange,false);
    this._NgbRadio_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    this._NgControlStatusGroup_0_5.checkHost(this,this,this._el_0,throwOnChange);
    this._NgControlStatus_2_8.checkHost(this,this,this._el_2,throwOnChange);
    const currVal_35:any = this.context.controlName;
    if (import3.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementProperty(this._el_6,'name',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = (this.context.controlName + '_No');
    if (import3.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementProperty(this._el_6,'id',currVal_36);
      this._expr_36 = currVal_36;
    }
    this._NgbRadio_6_3.checkHost(this,this,this._el_6,throwOnChange);
    const currVal_37:any = this.context.controlName;
    if (import3.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementProperty(this._el_11,'name',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = (this.context.controlName + '_NA');
    if (import3.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementProperty(this._el_11,'id',currVal_38);
      this._expr_38 = currVal_38;
    }
    this._NgbRadio_11_3.checkHost(this,this,this._el_11,throwOnChange);
    const currVal_39:any = this.context.controlName;
    if (import3.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementProperty(this._el_16,'name',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = (this.context.controlName + '_Yes');
    if (import3.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementProperty(this._el_16,'id',currVal_40);
      this._expr_40 = currVal_40;
    }
    this._NgbRadio_16_3.checkHost(this,this,this._el_16,throwOnChange);
  }
  destroyInternal():void {
    this._NgbRadio_6_3.ngOnDestroy();
    this._NgbRadio_11_3.ngOnDestroy();
    this._NgbRadio_16_3.ngOnDestroy();
    this._FormControlName_2_6.ngOnDestroy();
    this._FormGroupDirective_0_3.ngOnDestroy();
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._FormGroupDirective_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._DefaultValueAccessor_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbRadio_6_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbRadio_11_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgbRadio_16_3.handleEvent(eventName,$event) && result);
    return result;
  }
}